# Generated by Django 5.1.6 on 2026-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapp',
            name='scope',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write')], default='write', max_length=5),
        ),
    ]
